### ISSUE TITLE
What is the latest supported Batrium SW?

### ISSUE THREAD

**Issue by marval** [Batrium/WatchMonUdpListener#11]
Hello,

I have recently updated to 2.15.11 and the corresponding firmware on my WM4 and I can see that the messages have changed quite a bit. One message that I use particularly was the StatusRapid at 3e32 or 3e5a, but my WM never transmits any of these. I am connected to WiFi and it is set to verbose (thinking this will transmit everything possible):
![image](https://user-images.githubusercontent.com/1443599/115358428-ef437b00-a1bd-11eb-8ee2-3c408c6fc4e0.png)

Setting my config to throw everything at the MQTT server I get a list of the following IDs after a while:
![image](https://user-images.githubusercontent.com/1443599/115358507-08e4c280-a1be-11eb-8272-c61e4969578c.png)

Anybody able to point me at the right direction in order to get the data delivered from StatusRapid?

**Comment by daromer2** [comment]
For each update of a message the message version changes. A message consist of 2 parts. Example


Message 5635 and 5634. They are just message id 56 and version 34 and 35. So whats changed is first of all the version number bbut some messages have been deprecated as well. If you look at the payload folder it says what messages exist in what system. If you run the Watchmonudplistener it will also tell you if you lack payload info. 

So when upgrading you get new versions and the data end up on a new tag due to this. 

What you look for have changed name: Msg_3e33_StatusCellStats.js

Its now called statuscellstats and have same message id ie "3e" and was added 4 months ago.

/D

**Comment by marval** [comment]
Thanks! Figured it out. Seems the old message is now split in two so everything worked out when I caught them.
